AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - config/**/*.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

# Bundler
Bundler/OrderedGems:
  Enabled: false

# Metrics
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 6

Metrics/LineLength:
  Enabled: true
  Max: 100
  AllowHeredoc: true
  IgnoredPatterns: ['#.*']

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Style
Style/MixinUsage:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

# Lint
Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

# Layout
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
